"""Human-readable overview generation for current repository state."""

from datetime import date
from pathlib import Path
from urllib.parse import quote

from workrepo.clock import current_date
from workrepo.inbox import InboxReport
from workrepo.models import Document
from workrepo.review import next_review
from workrepo.state import RepositoryState
from workrepo.validation import inbox_report, require_repository

DASHBOARD_PATH = Path("DASHBOARD.md")
INACTIVE_PROJECT_STATUSES = frozenset({"completed", "cancelled"})
INACTIVE_AREA_STATUSES = frozenset({"retired"})
HEALTH_PRIORITY = {"red": 0, "amber": 1, "unknown": 2, "green": 3}


def generate_dashboard(root: Path, *, state: RepositoryState | None = None) -> Path:
    """Generate a deterministic Markdown dashboard from canonical state."""
    repository_state = state or require_repository(root)
    repository_root = repository_state.root
    documents = list(repository_state.documents)
    projects = _documents_of_type(documents, "project")
    areas = _documents_of_type(documents, "area")
    inbox = inbox_report(repository_state)
    content = "\n".join(
        (
            "# Work Dashboard",
            "",
            "<!-- Generated by `workrepo dashboard`; do not edit directly. -->",
            "",
            *_inbox_section(
                inbox,
                warn_after_days=repository_state.policy.inbox.warn_after_days,
            ),
            "",
            *_project_section(projects),
            "",
            *_area_section(
                areas,
                today=current_date(repository_state.policy.timezone),
            ),
            "",
        ),
    )
    output = repository_root / DASHBOARD_PATH
    output.write_text(content, encoding="utf-8")
    return output


def _inbox_section(
    report: InboxReport,
    *,
    warn_after_days: int,
) -> tuple[str, ...]:
    aging_items = sum(
        len(item.open_items) for item in report.files if item.age_days >= warn_after_days
    )
    oldest = f"{report.oldest_age_days} days" if report.oldest_age_days is not None else "none"
    summary = (
        " | ".join(
            (
                f"Open items: **{report.open_items}**",
                f"Needs review: **{aging_items}**",
                f"Oldest: **{oldest}**",
            ),
        ),
    )
    if not report.files:
        return ("## Inbox", "", *summary, "", "_Inbox is clear._")
    links = tuple(
        f"- [{item.capture_date.isoformat()}]({_path_link(item.path)})"
        f" — {len(item.open_items)} open, {item.age_days}d old"
        for item in sorted(report.files, key=lambda value: value.capture_date)
    )
    return ("## Inbox", "", *summary, "", *links)


def _project_section(documents: list[Document]) -> tuple[str, ...]:
    active = [
        document
        for document in documents
        if _metadata_text(document, "status") not in INACTIVE_PROJECT_STATUSES
    ]
    rows = tuple(_state_row(document) for document in _sort_by_health(active))
    return (
        "## Active projects",
        "",
        "| Project | Status | Health | Updated |",
        "| --- | --- | --- | --- |",
        *(rows or ("| _None_ |  |  |  |",)),
    )


def _area_section(
    documents: list[Document],
    *,
    today: date,
) -> tuple[str, ...]:
    visible = [
        document
        for document in documents
        if _metadata_text(document, "status") not in INACTIVE_AREA_STATUSES
    ]
    ordered = sorted(
        visible,
        key=lambda document: (
            not _is_review_overdue(document, today),
            HEALTH_PRIORITY.get(_metadata_text(document, "health"), 99),
            document.title.casefold(),
        ),
    )
    rows = tuple(_area_row(document, today) for document in ordered)
    return (
        "## Areas",
        "",
        "| Area | Status | Health | Last reviewed | Next review |",
        "| --- | --- | --- | --- | --- |",
        *(rows or ("| _None_ |  |  |  |  |",)),
    )


def _state_row(document: Document) -> str:
    title = _escape_text(document.title)
    link = _path_link(document.path)
    status = _escape_text(_metadata_text(document, "status"))
    health = _escape_text(_metadata_text(document, "health", default="unknown"))
    updated = _escape_text(_metadata_text(document, "updated"))
    return f"| [{title}]({link}) | {status} | {health} | {updated} |"


def _area_row(document: Document, today: date) -> str:
    title = _escape_text(document.title)
    link = _path_link(document.path)
    status = _escape_text(_metadata_text(document, "status"))
    health = _escape_text(_metadata_text(document, "health"))
    last_reviewed = _document_date(document, "last_reviewed")
    cycle = _metadata_text(document, "review_cycle")
    review_date = next_review(last_reviewed, cycle)
    review_text = review_date.isoformat()
    if review_date < today:
        review_text = f"**{review_text} (overdue)**"
    return (
        f"| [{title}]({link}) | {status} | {health} | {last_reviewed.isoformat()} | {review_text} |"
    )


def _documents_of_type(documents: list[Document], document_type: str) -> list[Document]:
    return sorted(
        (document for document in documents if document.metadata.get("type") == document_type),
        key=lambda document: document.title.casefold(),
    )


def _sort_by_health(documents: list[Document]) -> list[Document]:
    return sorted(
        documents,
        key=lambda document: (
            HEALTH_PRIORITY.get(_metadata_text(document, "health"), 99),
            document.title.casefold(),
        ),
    )


def _is_review_overdue(document: Document, today: date) -> bool:
    last_reviewed = _document_date(document, "last_reviewed")
    cycle = _metadata_text(document, "review_cycle")
    return next_review(last_reviewed, cycle) < today


def _document_date(document: Document, field: str) -> date:
    value = document.metadata[field]
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        return date.fromisoformat(value)
    message = f"{document.path}: {field} is not a date"
    raise ValueError(message)


def _metadata_text(document: Document, field: str, *, default: str = "") -> str:
    value = document.metadata.get(field, default)
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def _path_link(path: Path) -> str:
    return quote(path.as_posix(), safe="/:@-._~")


def _escape_text(value: str) -> str:
    return value.replace("|", r"\|").replace("]", r"\]")
