"""Human-readable overview generation for current repository state."""

import re
from datetime import date
from pathlib import Path
from urllib.parse import quote

from workrepo.models import Document
from workrepo.repository import read_documents
from workrepo.schema import load_schema

DASHBOARD_PATH = Path("DASHBOARD.md")
OPEN_ITEM_PATTERN = re.compile(r"^- \[ \]", flags=re.MULTILINE)
INACTIVE_PROJECT_STATUSES = frozenset({"completed", "cancelled"})


def generate_dashboard(root: Path) -> Path:
    """Generate a deterministic Markdown dashboard from canonical state."""
    repository_root = root.resolve()
    schema = load_schema(repository_root)
    documents = read_documents(repository_root)
    projects = _documents_of_type(documents, "project")
    areas = _documents_of_type(documents, "area")
    inbox_files = sorted(
        path
        for path in (repository_root / schema.inbox_root).glob("**/*.md")
        if path.name != "README.md"
    )
    content = "\n".join(
        (
            "# Work Dashboard",
            "",
            "<!-- Generated by `workrepo dashboard`; do not edit directly. -->",
            "",
            *_inbox_section(repository_root, inbox_files),
            "",
            *_project_section(projects),
            "",
            *_area_section(areas),
            "",
        ),
    )
    output = repository_root / DASHBOARD_PATH
    output.write_text(content, encoding="utf-8")
    return output


def _inbox_section(root: Path, paths: list[Path]) -> tuple[str, ...]:
    open_items = sum(
        len(OPEN_ITEM_PATTERN.findall(path.read_text(encoding="utf-8")))
        for path in paths
    )
    if not paths:
        return ("## Inbox", "", "Open items: **0**", "", "_Inbox is clear._")
    links = tuple(
        f"- [{_escape_text(path.stem)}]({_path_link(path.relative_to(root))})"
        for path in paths
    )
    return ("## Inbox", "", f"Open items: **{open_items}**", "", *links)


def _project_section(documents: list[Document]) -> tuple[str, ...]:
    active = [
        document
        for document in documents
        if _metadata_text(document, "status") not in INACTIVE_PROJECT_STATUSES
    ]
    rows = tuple(_state_row(document) for document in active)
    return (
        "## Active projects",
        "",
        "| Project | Status | Health | Updated |",
        "| --- | --- | --- | --- |",
        *(rows or ("| _None_ |  |  |  |",)),
    )


def _area_section(documents: list[Document]) -> tuple[str, ...]:
    rows = tuple(_state_row(document) for document in documents)
    return (
        "## Areas",
        "",
        "| Area | Status | Health | Updated |",
        "| --- | --- | --- | --- |",
        *(rows or ("| _None_ |  |  |  |",)),
    )


def _state_row(document: Document) -> str:
    title = _escape_text(document.title)
    link = _path_link(document.path)
    status = _escape_text(_metadata_text(document, "status"))
    health = _escape_text(_metadata_text(document, "health", default="unknown"))
    updated = _escape_text(_metadata_text(document, "updated"))
    return f"| [{title}]({link}) | {status} | {health} | {updated} |"


def _documents_of_type(documents: list[Document], document_type: str) -> list[Document]:
    return sorted(
        (
            document
            for document in documents
            if document.metadata.get("type") == document_type
        ),
        key=lambda document: document.title.casefold(),
    )


def _metadata_text(document: Document, field: str, *, default: str = "") -> str:
    value = document.metadata.get(field, default)
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def _path_link(path: Path) -> str:
    return quote(path.as_posix(), safe="/:@-._~")


def _escape_text(value: str) -> str:
    return value.replace("|", r"\|").replace("]", r"\]")
