"""Human and command-line navigation over canonical repository state."""

from dataclasses import dataclass
from pathlib import Path
from typing import Literal
from urllib.parse import quote

from workrepo.models import ContentDocument, Document
from workrepo.state import RepositoryState
from workrepo.validation import require_repository

NAVIGATION_PATH = Path("NAVIGATION.md")
INACTIVE_PROJECT_STATUSES = frozenset({"completed", "cancelled"})
LIBRARY_ROOT = Path("40-library")


@dataclass(frozen=True, slots=True)
class ContentFilter:
    """Optional filters shared by list and search operations."""

    document_type: str | None = None
    status: str | None = None
    health: str | None = None
    area_id: str | None = None
    group: str | None = None
    archive_scope: Literal["exclude", "include", "only"] = "exclude"


def list_content(
    state: RepositoryState,
    *,
    filters: ContentFilter | None = None,
    limit: int = 50,
) -> list[ContentDocument]:
    """Return deterministically ordered content matching explicit filters."""
    effective_filters = filters or ContentFilter()
    content: list[ContentDocument] = [*state.documents, *state.artifacts]
    matched = [
        item
        for item in content
        if _matches(
            item,
            effective_filters,
            archive_root=state.schema.archive_root,
        )
    ]
    return sorted(matched, key=_sort_key)[:limit]


def search_content(
    state: RepositoryState,
    query: str,
    *,
    filters: ContentFilter | None = None,
    limit: int = 50,
) -> list[ContentDocument]:
    """Search titles, IDs, metadata, and Markdown text with AND semantics."""
    terms = tuple(part.casefold() for part in query.split() if part)
    if not terms:
        message = "search query must not be empty"
        raise ValueError(message)
    candidates = list_content(
        state,
        filters=filters,
        limit=len(state.documents) + len(state.artifacts),
    )
    matched = [
        item
        for item in candidates
        if all(term in _searchable_text(state.root, item) for term in terms)
    ]
    return matched[:limit]


def generate_navigation(root: Path, *, state: RepositoryState | None = None) -> Path:
    """Generate a stable entry point for repositories with many documents."""
    repository_state = state or require_repository(root)
    projects = [
        document
        for document in repository_state.documents
        if document.metadata.get("type") == "project"
    ]
    areas = [
        document
        for document in repository_state.documents
        if document.metadata.get("type") == "area" and document.metadata.get("status") != "retired"
    ]
    active_projects = [
        project
        for project in projects
        if project.metadata.get("status") not in INACTIVE_PROJECT_STATUSES
    ]
    completed_projects = [
        project
        for project in projects
        if project.metadata.get("status") in INACTIVE_PROJECT_STATUSES
    ]
    content = "\n".join(
        (
            "# Repository Navigation",
            "",
            "<!-- Generated by `workrepo refresh`; do not edit directly. -->",
            "",
            "Use this page to browse durable work. Use `workrepo search TEXT` when the",
            "repository is too large to scan.",
            "",
            *_attention_section(active_projects),
            "",
            *_project_by_area_section(active_projects, areas),
            "",
            *_area_by_group_section(areas),
            "",
            *_library_section(repository_state),
            "",
            *_recently_completed_section(completed_projects),
            "",
        ),
    )
    output = repository_state.root / NAVIGATION_PATH
    output.write_text(content, encoding="utf-8")
    return output


def display_row(item: ContentDocument) -> str:
    """Render one compact, stable CLI row."""
    document_type = str(item.metadata.get("type", "artifact"))
    status = str(item.metadata.get("status", "-"))
    health = str(item.metadata.get("health", "-"))
    identifier = str(item.metadata.get("id", "-"))
    return (
        f"{document_type:<13} {status:<10} {health:<7} {identifier:<42} {item.title}  [{item.path}]"
    )


def _matches(
    item: ContentDocument,
    filters: ContentFilter,
    *,
    archive_root: Path,
) -> bool:
    metadata = item.metadata
    archived = item.path.is_relative_to(archive_root)
    archive_matches = not (
        (filters.archive_scope == "exclude" and archived)
        or (filters.archive_scope == "only" and not archived)
    )
    return (
        archive_matches
        and (filters.document_type is None or metadata.get("type") == filters.document_type)
        and (filters.status is None or metadata.get("status") == filters.status)
        and (filters.health is None or metadata.get("health") == filters.health)
        and (filters.group is None or metadata.get("group") == filters.group)
        and (filters.area_id is None or filters.area_id in _related_values(item))
    )


def _related_values(item: ContentDocument) -> tuple[str, ...]:
    value = item.metadata.get("related")
    if not isinstance(value, list):
        return ()
    return tuple(item for item in value if isinstance(item, str))


def _searchable_text(root: Path, item: ContentDocument) -> str:
    metadata = " ".join(_flatten_metadata(item.metadata))
    try:
        body = (root / item.path).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        body = ""
    return f"{item.title} {metadata} {body}".casefold()


def _flatten_metadata(value: object) -> list[str]:
    if isinstance(value, dict):
        return [text for item in value.values() for text in _flatten_metadata(item)]
    if isinstance(value, list):
        return [text for item in value for text in _flatten_metadata(item)]
    return [str(value)]


def _sort_key(item: ContentDocument) -> tuple[str, str, str]:
    return (
        str(item.metadata.get("type", "artifact")),
        item.title.casefold(),
        item.path.as_posix(),
    )


def _attention_section(projects: list[Document]) -> tuple[str, ...]:
    attention = [
        project
        for project in projects
        if project.metadata.get("status") == "blocked"
        or project.metadata.get("health") in {"red", "amber"}
    ]
    rows = tuple(f"- {_document_link(project)}" for project in sorted(attention, key=_sort_key))
    return ("## Needs attention", "", *(rows or ("_None._",)))


def _project_by_area_section(
    projects: list[Document],
    areas: list[Document],
) -> tuple[str, ...]:
    lines: list[str] = ["## Active projects by Area", ""]
    assigned: set[str] = set()
    for area in sorted(areas, key=_sort_key):
        area_id = str(area.metadata.get("id"))
        related = [project for project in projects if area_id in _related_values(project)]
        if not related:
            continue
        lines.extend((f"### {_document_link(area)}", ""))
        lines.extend(f"- {_document_link(project)}" for project in sorted(related, key=_sort_key))
        lines.append("")
        assigned.update(str(project.metadata.get("id")) for project in related)
    unassigned = [
        project for project in projects if str(project.metadata.get("id")) not in assigned
    ]
    if unassigned:
        lines.extend(("### No Area assigned", ""))
        lines.extend(
            f"- {_document_link(project)}" for project in sorted(unassigned, key=_sort_key)
        )
    if not projects:
        lines.append("_None._")
    return tuple(lines)


def _area_by_group_section(areas: list[Document]) -> tuple[str, ...]:
    grouped: dict[str, list[Document]] = {}
    for area in areas:
        group = str(area.metadata.get("group", "Ungrouped"))
        grouped.setdefault(group, []).append(area)
    lines: list[str] = ["## Areas by group", ""]
    for group, documents in sorted(grouped.items(), key=lambda item: item[0].casefold()):
        lines.extend((f"### {group}", ""))
        lines.extend(
            f"- {_document_link(document)}" for document in sorted(documents, key=_sort_key)
        )
        lines.append("")
    if not grouped:
        lines.append("_None._")
    return tuple(lines)


def _recently_completed_section(projects: list[Document]) -> tuple[str, ...]:
    ordered = sorted(
        projects,
        key=lambda project: str(project.metadata.get("updated", "")),
        reverse=True,
    )
    rows = tuple(f"- {_document_link(project)}" for project in ordered[:10])
    return ("## Recently completed projects", "", *(rows or ("_None._",)))


def _library_section(state: RepositoryState) -> tuple[str, ...]:
    counts: dict[str, int] = {}
    for document in state.documents:
        document_type = document.metadata.get("type")
        if not isinstance(document_type, str) or document_type not in state.schema.types:
            continue
        rule = state.schema.types[document_type]
        if (
            not rule.root.is_relative_to(LIBRARY_ROOT)
            or document.path.is_relative_to(state.schema.archive_root)
            or document.metadata.get("status") == "retired"
        ):
            continue
        counts[document_type] = counts.get(document_type, 0) + 1
    rows = []
    for document_type, count in sorted(
        counts.items(),
        key=lambda item: state.schema.types[item[0]].root.as_posix(),
    ):
        root = state.schema.types[document_type].root
        function = root.relative_to(LIBRARY_ROOT).parts[0].split("-", maxsplit=1)[-1].title()
        target = quote(f"{root.as_posix()}/", safe="/:@-._~")
        rows.append(f"| {function} | {document_type} | {count} | [{root}]({target}) |")
    return (
        "## Library",
        "",
        "| Function | Type | Current records | Location |",
        "| --- | --- | ---: | --- |",
        *(rows or ("| _None_ |  |  |  |",)),
    )


def _document_link(document: Document) -> str:
    target = quote(document.path.as_posix(), safe="/:@-._~")
    status = document.metadata.get("status")
    health = document.metadata.get("health")
    state = " · ".join(str(value) for value in (status, health) if value is not None)
    suffix = f" — {state}" if state else ""
    return f"[{document.title}]({target}){suffix}"
